import 'tailwindcss/tailwind.css'
import '@/styles/globals.css'
import Head from 'next/head'
import Link from "next/link";
import {Fragment} from "react";
import {Inter} from '@next/font/google'

const inter = Inter({subsets: ['latin']})
const nav = [{
    title: '杂谈',
    url: '/article',
}, {
    title: '朝花夕拾',
    url: '/luxun'
}, {
    title: '分享',
    url: '/share'
}]

function Layout({children}) {
    return (
            <Fragment>
                <Head>
                    <title>太虚环境</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>
                <div className={`${inter.className} max-w-prose mx-auto px-5`}>
                    <header className='pt-20 pb-10 m-auto'>
                        <h1 className='text-3xl font-bold pb-5'>太虚幻境</h1>
                        <nav className='flex gap-5 underline'>
                            {
                                nav.map(el => (
                                    <Link key={el.url} href={el.url}>{el.title}</Link>
                                ))
                            }
                        </nav>
                    </header>
                    <main className='pb-20'>
                        {children}
                    </main>
                    <footer className='text-center'>
                        <p>
                            莫等闲
                        </p>
                        <pre>
                        2023-2-18
                    </pre>
                    </footer>
                </div>
            </Fragment>
    )
}

export default function App({Component, pageProps}) {

    return (
        <Layout>
            <Component {...pageProps} />
        </Layout>

    )
}
