import 'tailwindcss/tailwind.css'
import '@/styles/globals.css'
import Head from 'next/head'
import {Fragment} from "react";
import {Inter} from '@next/font/google'

const inter = Inter({subsets: ['latin']})

function Layout({children}) {
    return (
        <Fragment>
            <Head>
                <title>太虚环境</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={`${inter.className} max-w-prose mx-auto px-5`}>
                <header className='pt-20 pb-10 m-auto'>
                    <h1 className='text-3xl font-bold pb-5'>太虚幻境</h1>
                    <nav className='flex gap-5 underline'>
                        <a href='#'>杂谈</a>
                        <a href='#'>朝花夕拾</a>
                        <a href='#'>分享</a>
                    </nav>
                </header>
                <main className='pb-20'>
                    {children}
                </main>
                <footer className='text-center'>
                    <p>
                        莫等闲
                    </p>
                    <pre>
                        2023-2-18
                    </pre>
                </footer>
            </div>
        </Fragment>
    )
}

export default function App({Component, pageProps}) {
    console.log({Component, pageProps})
    return (
        <Layout>
            <Component {...pageProps} />
        </Layout>
    )
}
