import {FC, Fragment, memo, useEffect, useState} from "react";
import Head from "next/head";
import Link from "next/link";
import {Inter} from '@next/font/google'
import {useRouter} from "next/router";
import Loading from "@/components/loading";

const inter = Inter({subsets: ['latin']})


const nav = [
    {
        // 记录所有离骚
        title: '杂谈',
        url: '/article',
    },
    {
        // 分享一周趣事并做点评
        title: '文心',
        url: '/news'
    },
    {
        // 分享文章内容
        title: '朝夕',
        url: '/luxun'
    },
    {
        // 技术分享
        title: '分享',
        url: '/share'
    },
]


interface MainProps {
    children: JSX.Element,
    isComplete: boolean
}

const MainComponent: FC<MainProps> = ({children, isComplete}) => {
    if (!isComplete) {
        return <Loading/>
    }

    return children
}

const Main = memo(MainComponent)


const NavComponent: FC = () => {
    return (
        <nav className='flex gap-5 underline'>
            {
                nav.map(el => (
                    <Link key={el.url} href={el.url}>{el.title}</Link>
                ))
            }
        </nav>
    )
}

const Nav = memo(NavComponent)


function Layout({children}) {
    const router = useRouter()
    const [isComplete, setComplete] = useState<boolean>(true)

    useEffect(() => {
        const routerStartHandler = () => setComplete(false)
        const routerCompleteHandler = () => setComplete(true)
        router.events.on('routeChangeStart', routerStartHandler)
        router.events.on('routeChangeComplete', routerCompleteHandler)
        // router.events.on('routeChangeError',routerErrorHandler)
        return () => {
            router.events.off('routeChangeComplete', routerCompleteHandler)
            router.events.off('routeChangeStart', routerStartHandler)
        }
    }, [router.events])

    return (
        <Fragment>
            <Head>
                <title>太虚幻境</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <div className={`${inter.className} max-w-prose mx-auto px-5 h-[100vh]`}>
                <header className=' pb-10 m-auto'>
                    <h1 id='header' className='pt-20 text-3xl font-bold pb-5'><Link href='/'>太虚幻境</Link></h1>
                    <Nav/>
                </header>
                <Main isComplete={isComplete}>{children}</Main>
                <footer className='text-center text-[#94a3b8] mt-6 pb-6'>
                    <pre>
                       莫等闲 &copy; 2023
                    </pre>
                </footer>
            </div>
        </Fragment>
    )
}

export default memo(Layout)
